services:
  mysql:
    container_name: mysql_container
    image: mysql:8.4.3
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_USER=thanhng
      - MYSQL_PASSWORD=qwerty
      - MYSQL_DATABASE=docker_db
      - MYSQL_DEFAULT_AUTHENTICATION_PLUGIN=mysql_native_password
    networks:
      - mysql-net
    ports:
      - "3306:3306"

networks:
  mysql-net:
