services:
  backend:
    container_name: backend_container
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - be-net
    environment:
      - MYSQL_HOST=192.168.88.217
      - REDIS_HOST=192.168.88.217
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_USER=thanhng
      - MYSQL_PASSWORD=qwerty
      - MYSQL_DATABASE=docker_db
      - MYSQL_DEFAULT_AUTHENTICATION_PLUGIN=mysql_native_password
      - MYSQL_TCP_PORT=3308
    ports:
      - "8386:8386"

networks:
  be-net:
