services:
  backend:
    container_name: backend_container
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - tulip-net
    environment:
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_USER=thanhng
      - MYSQL_PASSWORD=qwerty
      - MYSQL_DATABASE=docker_db
      - MYSQL_DEFAULT_AUTHENTICATION_PLUGIN=mysql_native_password
      - MYSQL_TCP_PORT=3307
    depends_on:
      - mysql
      - redis
    ports:
      - "8386:8386"

  mysql:
    extends:
      file: docker-compose-mysql.yml
      service: mysql

  redis:
    extends:
      file: docker-compose-redis.yml
      service: redis

networks:
  tulip-net:
    external: true
